version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base

    container_name: app

    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: yarn dev
